### ISSUE TITLE
Unitest Error

### ISSUE THREAD

**Issue by wangtianrui** [lava-nc/lava-dl#176]
**Describe the bug**
Follow the official tutorial. I installed the lava first. Then lava-dl was installed. But I couldn't pass the unit test.

**To reproduce current behavior**
1. I installed the lava. And passed the unitest.
```python
Required test coverage of 65.0% reached. Total coverage: 87.74%
=================================== 396 passed, 5 skipped, 4 warnings in 832.50s (0:13:52) ===================================
```
2. I installed the lava-dl
```shell
export PYTHONPATH=/home/studios/lava/src
git clone git@github.com:lava-nc/lava-dl.git
cd lava-dl
curl -sSL https://install.python-poetry.org | python3 -
poetry config virtualenvs.in-project true
poetry install
pytest
```
but I cant pass the unitest:
```shell
The above exception was the direct cause of the following exception:
tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_threshold.py:55: in <module>
    voltage = slayer.neuron.dynamics.leaky_integrator.dynamics(
src/lava/lib/dl/slayer/neuron/dynamics/leaky_integrator.py:95: in dynamics
    output = Accelerated.leaky_integrator.dynamics(
src/lava/lib/dl/slayer/utils/utils.py:14: in __get__
    return staticmethod(self.fget).__get__(None, owner)()
src/lava/lib/dl/slayer/neuron/dynamics/leaky_integrator.py:40: in leaky_integrator
    Accelerated.module = load(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1202: in load
    return _jit_compile(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1425: in _jit_compile
    _write_ninja_file_and_build_library(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1537: in _write_ninja_file_and_build_library
    _run_ninja_build(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1824: in _run_ninja_build
    raise RuntimeError(message) from e
E   RuntimeError: Error building extension 'dynamics_v5': [1/2] :/usr/local/cuda:/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v5 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/TH -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /home/wang/.conda/envs/lava/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/wang/codes/py/XTeam/studios/lava-dl/src/lava/lib/dl/slayer/neuron/dynamics/leaky_integrator.cu -o leaky_integrator.cuda.o 
E   FAILED: leaky_integrator.cuda.o 
E   :/usr/local/cuda:/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v5 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/TH -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /home/wang/.conda/envs/lava/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/wang/codes/py/XTeam/studios/lava-dl/src/lava/lib/dl/slayer/neuron/dynamics/leaky_integrator.cu -o leaky_integrator.cuda.o 
E   /bin/sh: 1: :/usr/local/cuda:/usr/local/cuda/bin/nvcc: not found
E   ninja: build stopped: subcommand failed.
_____ ERROR collecting tests/lava/lib/dl/slayer/neuron/dynamics/test_leaky_integrator.py _____
ImportError while importing test module '/home/wang/codes/py/XTeam/studios/lava-dl/tests/lava/lib/dl/slayer/neuron/dynamics/test_leaky_integrator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/wang/.conda/envs/lava/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/lava/lib/dl/slayer/neuron/dynamics/test_leaky_integrator.py:55: in <module>
    output0 = slayer.neuron.dynamics.leaky_integrator.dynamics(
src/lava/lib/dl/slayer/neuron/dynamics/leaky_integrator.py:95: in dynamics
    output = Accelerated.leaky_integrator.dynamics(
src/lava/lib/dl/slayer/utils/utils.py:14: in __get__
    return staticmethod(self.fget).__get__(None, owner)()
src/lava/lib/dl/slayer/neuron/dynamics/leaky_integrator.py:40: in leaky_integrator
    Accelerated.module = load(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1202: in load
    return _jit_compile(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1450: in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1844: in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
E   ImportError: /home/wang/.cache/torch_extensions/py39_cu102/dynamics/dynamics_v5.so: cannot open shared object file: No such file or directory
________ ERROR collecting tests/lava/lib/dl/slayer/neuron/dynamics/test_resonator.py _________
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1808: in _run_ninja_build
    subprocess.run(
/home/wang/.conda/envs/lava/lib/python3.9/subprocess.py:528: in run
    raise CalledProcessError(retcode, process.args,
E   subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:
tests/lava/lib/dl/slayer/neuron/dynamics/test_resonator.py:62: in <module>
    re, im = slayer.neuron.dynamics.resonator.dynamics(
src/lava/lib/dl/slayer/neuron/dynamics/resonator.py:118: in dynamics
    real, imag = _ResDynamics.apply(
src/lava/lib/dl/slayer/neuron/dynamics/resonator.py:196: in forward
    _real, _imag = Accelerated.resonator.fwd(
src/lava/lib/dl/slayer/utils/utils.py:14: in __get__
    return staticmethod(self.fget).__get__(None, owner)()
src/lava/lib/dl/slayer/neuron/dynamics/resonator.py:39: in resonator
    Accelerated.module = load(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1202: in load
    return _jit_compile(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1425: in _jit_compile
    _write_ninja_file_and_build_library(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1537: in _write_ninja_file_and_build_library
    _run_ninja_build(
/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py:1824: in _run_ninja_build
    raise RuntimeError(message) from e
E   RuntimeError: Error building extension 'dynamics_v6': [1/2] :/usr/local/cuda:/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v6 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/TH -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /home/wang/.conda/envs/lava/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/wang/codes/py/XTeam/studios/lava-dl/src/lava/lib/dl/slayer/neuron/dynamics/resonator.cu -o resonator.cuda.o 
E   FAILED: resonator.cuda.o 
E   :/usr/local/cuda:/usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v6 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/TH -isystem /home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/include/THC -isystem :/usr/local/cuda:/usr/local/cuda/include -isystem /home/wang/.conda/envs/lava/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14 -c /home/wang/codes/py/XTeam/studios/lava-dl/src/lava/lib/dl/slayer/neuron/dynamics/resonator.cu -o resonator.cuda.o 
E   /bin/sh: 1: :/usr/local/cuda:/usr/local/cuda/bin/nvcc: not found
E   ninja: build stopped: subcommand failed.
====================================== warnings summary ======================================
../../../../../.conda/envs/lava/lib/python3.9/site-packages/pytest_cov/plugin.py:256
  /home/wang/.conda/envs/lava/lib/python3.9/site-packages/pytest_cov/plugin.py:256: PytestDeprecationWarning: The hookimpl CovPlugin.pytest_configure_node uses old-style configuration options (marks or attributes).
  Please use the pytest.hookimpl(optionalhook=True) decorator instead
   to configure the hooks.
   See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
    def pytest_configure_node(self, node):

../../../../../.conda/envs/lava/lib/python3.9/site-packages/pytest_cov/plugin.py:265
  /home/wang/.conda/envs/lava/lib/python3.9/site-packages/pytest_cov/plugin.py:265: PytestDeprecationWarning: The hookimpl CovPlugin.pytest_testnodedown uses old-style configuration options (marks or attributes).
  Please use the pytest.hookimpl(optionalhook=True) decorator instead
   to configure the hooks.
   See https://docs.pytest.org/en/latest/deprecations.html#configuring-hook-specs-impls-using-markers
    def pytest_testnodedown(self, node, error):

tests/lava/lib/dl/netx/test_blocks.py:32
  /home/wang/codes/py/XTeam/studios/lava-dl/tests/lava/lib/dl/netx/test_blocks.py:32: PytestCollectionWarning: cannot collect test class 'TestRunConfig' because it has a __init__ constructor (from: tests/lava/lib/dl/netx/test_blocks.py)
    class TestRunConfig(RunConfig):

tests/lava/lib/dl/netx/test_hdf5.py:29
  /home/wang/codes/py/XTeam/studios/lava-dl/tests/lava/lib/dl/netx/test_hdf5.py:29: PytestCollectionWarning: cannot collect test class 'TestRunConfig' because it has a __init__ constructor (from: tests/lava/lib/dl/netx/test_hdf5.py)
    class TestRunConfig(RunConfig):

../../../../../.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:121
  /home/wang/.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
    warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)

../../../../../.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
  /home/wang/.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)

../../../../../.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
../../../../../.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
../../../../../.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
../../../../../.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
../../../../../.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
../../../../../.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:2870
  /home/wang/.conda/envs/lava/lib/python3.9/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    declare_namespace(pkg)




FAIL Required test coverage of 45.0% not reached. Total coverage: 32.69%
================================== short test summary info ===================================
ERROR tests/lava/lib/dl/slayer/neuron/test_adrf.py - RuntimeError: Error building extension 'dynamics': [1/2] :/usr/local/cuda:/usr/local/cuda...
ERROR tests/lava/lib/dl/slayer/neuron/test_adrf_iz.py - RuntimeError: Error building extension 'dynamics_v1': [1/2] :/usr/local/cuda:/usr/local/c...
ERROR tests/lava/lib/dl/slayer/neuron/test_alif.py - RuntimeError: Error building extension 'dynamics_v2': [1/2] :/usr/local/cuda:/usr/local/c...
ERROR tests/lava/lib/dl/slayer/neuron/test_cuba.py
ERROR tests/lava/lib/dl/slayer/neuron/test_rf.py - RuntimeError: Error building extension 'dynamics_v3': [1/2] :/usr/local/cuda:/usr/local/c...
ERROR tests/lava/lib/dl/slayer/neuron/test_rf_iz.py
ERROR tests/lava/lib/dl/slayer/neuron/test_sigma_delta.py
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_phase_th.py
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_resonator.py - RuntimeError: Error building extension 'dynamics_v4': [1/2] :/usr/local/cuda:/usr/local/c...
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_threshold.py - RuntimeError: Error building extension 'dynamics_v5': [1/2] :/usr/local/cuda:/usr/local/c...
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_leaky_integrator.py
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_resonator.py - RuntimeError: Error building extension 'dynamics_v6': [1/2] :/usr/local/cuda:/usr/local/c...
!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 12 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!
============================== 12 warnings, 12 errors in 7.53s ===============================
```

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. Remove section otherwise.

**Environment (please complete the following information):**
 - Linux version 4.15.0-142-generic (buildd@lgw01-amd64-039) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12))
 - torch=1.12.1     cuda=11.3
 - Lava version [e.g. 0.6.0]

**Comment by bamsumit** [comment]
Hi @wangtianrui it looks like you are trying to install it on a GPU machine, but you don't have a `nvcc` compiler installed or configured correctly.

This is the error message from your logs
```bash
E   /bin/sh: 1: :/usr/local/cuda:/usr/local/cuda/bin/nvcc: not found
```

The solution is to install `nvcc` compiler on your machine with the same cuda version as your cuda runtime.
Cuda runtime can be viewed as
```bash
nvidia-smi | grep CUDA
```

Verify `nvcc` installation by running
```bash
nvcc --version
```

**Finally make sure torch cuda version also matches**.

**Comment by wangtianrui** [comment]
Thank you for your reply. I just confirmed it once. My nvcc and pytorch are working fine.
```shell
(lava) wang@speech-ubuntu:~/codes/py/studios/lava$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0

(lava) wang@speech-ubuntu:~/codes/py/studios/lava-dl$ which nvcc 
/usr/local/cuda/bin/nvcc

(lava) wang@speech-ubuntu:~/codes/py/studios/lava-dl$ nvidia-smi | grep CUDA
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3 

(lava) wang@speech-ubuntu:~/codes/py/studios/lava-dl$ python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```
I also try to check the /usr/local/cuda and /usr/local/cuda/bin/nvcc
```shell
(lava) wang@speech-ubuntu:~/codes/py/studios/lava-dl$ ls  /usr/local/cuda
bin  compute-sanitizer  DOCS  EULA.txt  extras  include  lib64  libnvvp  nsightee_plugins  nvml  nvvm  nvvm-prev  README  samples  share  src  targets  tools  version.json
(lava) wang@speech-ubuntu:~/codes/py/studios/lava-dl$ ls /usr/local/cuda/bin/
bin2c              crt       cuda-gdbserver                cu++filt   ncu                          nsight-sys     nsys-ui       nvdisasm      nv-nsight-cu-cli  nvvp
computeprof        cudafe++  cuda-install-samples-11.3.sh  cuobjdump  ncu-ui                       nsys           nvcc          nvlink        nvprof            ptxas
compute-sanitizer  cuda-gdb  cuda-memcheck                 fatbinary  nsight_ee_plugins_manage.sh  nsys-exporter  nvcc.profile  nv-nsight-cu  nvprune
```
And I can train models on gpu with regular pytorch codes. But I cant do that with lava-dl modules.  And I cant pass the unitest as I shared with you earlier.

**Comment by wangtianrui** [comment]
In addition. My codes were running in conda's virtual environment. I wonder if there will be any unexpected problems with the conda env?

**Comment by wangtianrui** [comment]
update:

I reinstall the repo, and the error were changed:


```shell
export CUDA_HOME=/usr/local/cuda-11.3
export PYTHONPATH=/home/wang/codes/py/XTeam/studios/lava/src
conda activate lava

(lava) wang@speech-ubuntu:~/codes/py/XTeam/studios/lava-dl$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
(lava) wang@speech-ubuntu:~/codes/py/XTeam/studios/lava-dl$ echo $PYTHONPATH
/home/wang/codes/py/XTeam/studios/lava/src
(lava) wang@speech-ubuntu:~/codes/py/XTeam/studios/lava-dl$ nvidia-smi | grep CUDA
| NVIDIA-SMI 465.19.01    Driver Version: 465.19.01    CUDA Version: 11.3     |
(lava) wang@speech-ubuntu:~/codes/py/XTeam/studios/lava-dl$ python
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
True
```

```shell

FAIL Required test coverage of 45.0% not reached. Total coverage: 32.69%
==================================================== short test summary info ====================================================
ERROR tests/lava/lib/dl/slayer/neuron/test_adrf.py - RuntimeError: Error building extension 'dynamics': [1/2] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics -DTO...
ERROR tests/lava/lib/dl/slayer/neuron/test_adrf_iz.py - RuntimeError: Error building extension 'dynamics_v1': [1/2] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v...
ERROR tests/lava/lib/dl/slayer/neuron/test_alif.py - RuntimeError: Error building extension 'dynamics_v2': [1/2] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v...
ERROR tests/lava/lib/dl/slayer/neuron/test_cuba.py
ERROR tests/lava/lib/dl/slayer/neuron/test_rf.py - RuntimeError: Error building extension 'dynamics_v3': [1/2] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v...
ERROR tests/lava/lib/dl/slayer/neuron/test_rf_iz.py
ERROR tests/lava/lib/dl/slayer/neuron/test_sigma_delta.py
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_phase_th.py
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_resonator.py - RuntimeError: Error building extension 'dynamics_v4': [1/2] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v...
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_adaptive_threshold.py - RuntimeError: Error building extension 'dynamics_v5': [1/2] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v...
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_leaky_integrator.py
ERROR tests/lava/lib/dl/slayer/neuron/dynamics/test_resonator.py - RuntimeError: Error building extension 'dynamics_v6': [1/2] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=dynamics_v...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 12 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================== 12 warnings, 12 errors in 221.87s (0:03:41) ==========================================
```

**Comment by wangtianrui** [comment]
Thank you for your reply. Here are the results of these commands:

```shell
(lava) wang@speech-ubuntu:~/codes/py/XTeam$ which nvcc
/usr/local/cuda/bin/nvcc
al/cuda(lava) wang@speech-ubuntu:~/codes/py/XTeam$ ls /usr/local/cuda/bin/nvcc
/usr/local/cuda/bin/nvcc
(lava) wang@speech-ubuntu:~/codes/py/XTeam$ ls /usr/local/cuda
bin                DOCS      extras   lib64    nsightee_plugins  nvvm       README   share  targets  version.json
compute-sanitizer  EULA.txt  include  libnvvp  nvml              nvvm-prev  samples  src    tools
```

**Comment by bamsumit** [comment]
Can you try this solution: https://github.com/pytorch/extension-cpp/issues/51#issuecomment-958645506

**Comment by wangtianrui** [comment]
I tried your solution, but it also dont work for me.
```shell
export CUDA_HOME=/usr/local/cuda-11.3
export PYTHONPATH=/home/wang/codes/py/XTeam/studios/lava/src
export PATH="$PATH:/usr/local/cuda-11.3/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda-11.3/lib64"
```

I meet the same error when training models.

```shell
Traceback (most recent call last):
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/train.py", line 84, in <module>
    solver.train()
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/base/Solver.py", line 103, in train
    train_avg_loss = self._run_one_epoch(epoch, training=True)
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/base/Solver.py", line 151, in _run_one_epoch
    batch_loss = self.model(x.cuda(), y.cuda(), training).mean()
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 168, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 178, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
    raise exception
ImportError: Caught ImportError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/train.py", line 47, in forward
    denoised_abs = self.denoiser(noisy_abs)
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/model.py", line 45, in forward
    x = block(x)
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/lava/lib/dl/slayer/block/base.py", line 518, in forward
    x = delay(x, 1)
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/lava/lib/dl/slayer/axon/delay.py", line 35, in delay
    return _delayFunctionNoGradient.apply(input, delay_val, sampling_time)
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/lava/lib/dl/slayer/axon/delay.py", line 158, in forward
    output = shift(input, delay_val, sampling_time)
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/lava/lib/dl/slayer/utils/time/shift.py", line 139, in shift
    return Accelerated.shift.shift(
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/lava/lib/dl/slayer/utils/utils.py", line 14, in __get__
    return staticmethod(self.fget).__get__(None, owner)()
  File "/home/wang/codes/py/XTeam/baseline_solution/sdnn/lava/lib/dl/slayer/utils/time/shift.py", line 36, in shift
    Accelerated.module = load(
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1450, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/wang/.conda/envs/lava/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1844, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: /home/wang/.cache/torch_extensions/py39_cu102/shift/shift.so: cannot open shared object file: No such file or directory
```

**Comment by bamsumit** [comment]
Okay that's progress. Can you uninstall `torch`, `torchvision` and `torchaudio` and reinstall it again targeting cuda 11.3 (I suspect it is installed for cuda 11.7, which is the default now)
* `pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113` OR
* `conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch`

**Comment by wangtianrui** [comment]
No. My torch, torchvision and torchaudio were targeting cuda 11.3
```shell
(lava) wang@speech-ubuntu:~/codes/py/XTeam$ conda list | grep torch
ffmpeg                    4.3                  hf484d3e_0    pytorch
pytorch                   1.12.1          py3.9_cuda11.3_cudnn8.3.2_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
torch                     1.12.1                   pypi_0    pypi
torchaudio                0.12.1               py39_cu113    pytorch
torchvision               0.13.1                   pypi_0    pypi
```
The normal pytorch models codes can be trained correctly, but the model with lava-dl cannot. The cause of the problem seems to be "lava/lib/dl/slayer/utils/time/shift.py".

**Comment by wangtianrui** [comment]
Hello, I have solved the problem of training. I just put the src/lava/ folder directly under the project directory without installing the lava-dl. In this way, it can be trained without errors.  I presume that some environment bindings are incompatible when installing lava.

Thank you for your reply. Wish you a happy life. @bamsumit

**Comment by bamsumit** [comment]
Great. Thanks for letting us know.
