### ISSUE TITLE
About installation procedure unittests

### ISSUE THREAD

**Issue by ahmetakman** [lava-nc/lava-dl#41]
Objective of issue:
Hello,
I have got an error while following the installation procedure on my Ubuntu 20.04 system. I have installed the lava core packet beforehand. I could not figure out why such an error I am getting so I am giving the whole terminal output.

**Lava version:**
- [ ] **0.3.0** (feature release)
- [ ] **0.2.1** (bug fixes)
- [x] **0.2.0** (current version)
- [ ] **0.1.2**

**I'm submitting a ...** 

- [x ] bug report
- [ ] feature request
- [ ] documentation request

**Current behavior:**

- 

user@user-pc1:~/lava-dl$ pyb -E unit
PyBuilder version 0.13.5
Build started at 2022-03-04 15:33:17
------------------------------------------------------------
[INFO]  Installing or updating plugin "pypi:pybuilder_bandit, module name 'pybuilder_bandit'"
[INFO]  Processing plugin packages 'pybuilder_bandit' to be installed with {}
[INFO]  Activated environments: unit
[INFO]  Building lava-dl version 0.1.1
[INFO]  Executing build in /home/user/lava-dl
[INFO]  Going to execute tasks: analyze, publish
[INFO]  Processing plugin packages 'flake8~=4.0' to be installed with {'upgrade': True}
[INFO]  Processing plugin packages 'pypandoc~=1.4' to be installed with {'upgrade': True}
[INFO]  Processing plugin packages 'setuptools>=38.6.0' to be installed with {'upgrade': True}
[INFO]  Processing plugin packages 'sphinx_rtd_theme' to be installed with {}
[INFO]  Processing plugin packages 'sphinx_tabs' to be installed with {}
[INFO]  Processing plugin packages 'twine>=1.15.0' to be installed with {'upgrade': True}
[INFO]  Processing plugin packages 'unittest-xml-reporting~=3.0.4' to be installed with {'upgrade': True}
[INFO]  Processing plugin packages 'wheel>=0.34.0' to be installed with {'upgrade': True}
[INFO]  Creating target 'build' VEnv in '/home/user/lava-dl/target/venv/build/cpython-3.8.10.final.0'
[INFO]  Processing dependency packages 'lava' from git+https://github.com/lava-nc/lava.git to be installed with {'force_reinstall': True}
[INFO]  Processing dependency packages 'requirements.txt' to be installed with {}
[INFO]  Creating target 'test' VEnv in '/home/user/lava-dl/target/venv/test/cpython-3.8.10.final.0'
[INFO]  Processing dependency packages 'requirements.txt' to be installed with {}
[INFO]  Executing flake8 on project sources.
[INFO]  Running unit tests
[INFO]  Executing unit tests from Python modules in /home/user/lava-dl/tests/lava
[INFO]  Executed 82 unit tests
[ERROR] Test has error: unittest.loader._FailedTest.test_hdf5
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/usr/lib/python3.8/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_hdf5
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/user/lava-dl/tests/lava/lib/dl/netx/test_hdf5.py", line 18, in <module>
    from lava.lib.dl import netx
  File "/home/user/lava-dl/src/lava/lib/dl/netx/__init__.py", line 4, in <module>
    from . import hdf5
  File "/home/user/lava-dl/src/lava/lib/dl/netx/hdf5.py", line 15, in <module>
    from lava.proc.sdn.process import Sigma, Delta, SigmaDelta
ModuleNotFoundError: No module named 'lava.proc.sdn'

[ERROR] Test has error: unittest.loader._FailedTest.test_blocks
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/usr/lib/python3.8/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_blocks
Traceback (most recent call last):
  File "/usr/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/user/lava-dl/tests/lava/lib/dl/netx/test_blocks.py", line 20, in <module>
    from lava.lib.dl.netx.blocks.process import Dense, Conv, Input
  File "/home/user/lava-dl/src/lava/lib/dl/netx/__init__.py", line 4, in <module>
    from . import hdf5
  File "/home/user/lava-dl/src/lava/lib/dl/netx/hdf5.py", line 15, in <module>
    from lava.proc.sdn.process import Sigma, Delta, SigmaDelta
ModuleNotFoundError: No module named 'lava.proc.sdn'

------------------------------------------------------------
BUILD FAILED - There were 2 error(s) and 0 failure(s) in unit tests (pybuilder/plugins/python/unittest_plugin.py:109)
------------------------------------------------------------
Build finished at 2022-03-04 15:39:45
Build took 387 seconds (387886 ms)

**Expected behavior:**

- 

**Steps to reproduce:**

- 

**Related code:**

```
insert short code snippets here
```

**Other information:**

```
insert the output from lava debug here
```

**Comment by bamsumit** [comment]
Hi @ahmetakman it looks like you are using the latest version of lava-dl but not the latest lava repo. Can you update your lava to the latest version from git and try it again.

**Comment by ahmetakman** [comment]
I am using 0.2.0 for lava-nc and 0.1.1 for lava-dl. I have struggled to install following the normal install procedure from git directly (As can be observed from the issues I have opened). So, I had to install the from binary by release version. I assume you mean the repository update as the latest version. I will try to install them again from scratch.

**Comment by bamsumit** [comment]
Great. Can we close this issue then?

**Comment by ahmetakman** [comment]
Yeah, of course.
